spring:
    datasource:
      dbcp2:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.30.1/resouseshare?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: root123
    jpa:
      hibernate:
         ddl-auto: update
         show-sql: true